#services:
#  postgres:
#    image: postgres:15
#    environment:
#      POSTGRES_DB: arth
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: userpass
#    ports:
#      - "5432:5432"
#
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres