spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/arth
    username: ${ARTH_DB_USERNAME}
    password: ${ARTH_DB_PASSWORD}