spring:
  application:
    name: Arth-Banking
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/arth
    username: user
    password: userpass
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.web: DEBUG
    org.apache.tomcat.util.http: DEBUG
    web: DEBUG
testcontainers.reuse.enable: true
