spring:
  application:
    name: Arth-Banking
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/arth
    username: ${ARTH_DB_USERNAME}
    password: ${ARTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


logging:
  level:
    org.springframework.web: DEBUG
    org.apache.tomcat.util.http: DEBUG
    web: DEBUG